# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hired',
            field=models.CharField(max_length=255),
        ),
    ]
